### ISSUE TITLE
Error starting up

### ISSUE THREAD

**Issue by bsclifton** [brave/electron#118]
* Electron version: HEAD for chromium54
* Operating system: Windows 10 Pro x64

When trying to run `browser-laptop`, I am getting output like so:
```
C:\GitHub\browser-laptop-bootstrap\src\out\Release\brave.exe --user-data-dir=brave-development --enable-logging --v=0 C:\GitHub\browser-laptop-bootstrap\src\browser-laptop
(node:5364) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: Failed to get path
    at getPepperFlashPath (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\flash.js:24:16)
    at Object.module.exports.checkFlashInstalled (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\flash.js:90:39)
    at Object.module.exports.init (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\flash.js:116:18)
    at flashReducer (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\app\browser\reducers\flashReducer.js:15:13)
    at handleAppAction (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\stores\appStore.js:366:14)
    at C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\dispatcher\appDispatcher.js:67:23
    at Array.forEach (native)
    at AppDispatcher.dispatch (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\dispatcher\appDispatcher.js:64:20)
    at Object.setState (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\js\actions\appActions.js:17:19)
    at loadAppStatePromise.then (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\app\index.js:409:16)
```
My guess is that my older existing profile doesn't have the value required that is being searched for

Temporary work-around for me was to comment out the flashReducer in `js/stores/appStore.js` (inside handleAppAction).  

cc @bridiver

**Comment by bridiver** [comment]
do you have flash installed? It looks like `GetPath` throws an error if it doesn't find a value. We should change that.

**Comment by bsclifton** [comment]
@bridiver no I don't have flash installed actually

**Comment by bridiver** [comment]
ok, I know what the problem is then
