### ISSUE TITLE
Bootstrap issue with electron build?

### ISSUE THREAD

**Issue by seaglemd** [brave/electron#123]
* Electron version: 2.0.4
* Operating system: Windows 10
About a month ago I pulled and built electron and brave for added extension support without any issue. Last few days I have tried different versions of node, python, etc, to get electron to build, but it seems to be missing some files?

Following directions for cloning electron git clone https://github.com/brave/electron and then trying to execute either:

npm run bootstrap 
or
python .\script\bootstrap.py -v -target_arch=x64

both result in errors, different ones.

Trying to bootstrap from npm after cd electron produces.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle electron@2.0.4~prebootstrap: electron@2.0.4
6 silly lifecycle electron@2.0.4~prebootstrap: no script for prebootstrap, continuing
7 info lifecycle electron@2.0.4~bootstrap: electron@2.0.4
8 verbose lifecycle electron@2.0.4~bootstrap: unsafe-perm in lifecycle true
9 verbose lifecycle electron@2.0.4~bootstrap: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\MirageID\electron\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files\nodejs\;C:\Users\MatthewSeagle\AppData\Local\Microsoft\WindowsApps;C:\Users\MatthewSeagle\AppData\Local\atom\bin;C:\depottools;C:\Python27;C:\Program Files\nodejs\;C:\Users\MatthewSeagle\AppData\Roaming\npm
10 verbose lifecycle electron@2.0.4~bootstrap: CWD: C:\MirageID\electron
11 silly lifecycle electron@2.0.4~bootstrap: Args: [ '/d /s /c', 'python ./script/bootstrap.py' ]
12 silly lifecycle electron@2.0.4~bootstrap: Returned: code: 1  signal: null
13 info lifecycle electron@2.0.4~bootstrap: Failed to exec bootstrap script
14 verbose stack Error: electron@2.0.4 bootstrap: `python ./script/bootstrap.py`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron@2.0.4
16 verbose cwd C:\MirageID\electron
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error electron@2.0.4 bootstrap: `python ./script/bootstrap.py`
22 error Exit status 1
23 error Failed at the electron@2.0.4 bootstrap script 'python ./script/bootstrap.py'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     python ./script/bootstrap.py
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
The error that seems more significant almost is before the debug log is output comes from windows and it states it cannot find a file in vendor\requests

```
> electron@2.0.4 bootstrap C:\MirageID\electron
> python ./script/bootstrap.py

Traceback (most recent call last):
  File "./script/bootstrap.py", line 79, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 32, in main
    setup_python_libs()
  File "./script/bootstrap.py", line 59, in setup_python_libs
    with scoped_cwd(os.path.join(VENDOR_DIR, lib)):
  File "C:\depottools\python276_bin\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\MirageID\electron\script\lib\util.py", line 56, in scoped_cwd
    os.chdir(path)
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\MirageID\\electron\\vendor\\requests'
```
If I try to run bootstrap from the script dir using python python .\script\bootstrap.py -v -target_arch=x64 it gives me an error relating bootstrap.py unrecognized arguments --target_arch=x64

any reason why a month ago this built fine and now it won't? Updates? Documentation for clean build not updated? I'm able to build brave fine.

**Comment by bridiver** [comment]
there are significant changes for 2.0.4 and we haven't had a chance to provide good documentation for everything yet, but you can get started with https://github.com/brave/browser-laptop-bootstrap. You should expect both `npm run init` and `npm run build` to take a very long time the first time through because it downloads chromium src and builds the parts we need use. We're in the process of configuring sccache to speed up the initial build. electron and browser-laptop will both be under src as subdirectories of chromium src. The old bootstrap/build scripts should not be used directly anymore
